name: ballistic-labyrinth

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8137:80"
    depends_on:
      manager:
        condition: service_healthy
    restart: unless-stopped

  manager:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - room-logs:/app/roomlogs
    restart: unless-stopped

volumes:
  room-logs:
